default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['SOUL_SHARE_DATABASE_USER'] %>
  password: <%= ENV['SOUL_SHARE_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: soul_share_development

test:
  <<: *default
  database: soul_share_test

production:
  <<: *default
  database: soul_share_production
  username: soul_share
  password: <%= ENV['SOUL_SHARE_DATABASE_PASSWORD'] %>